<?= $this->extend('layout/navbar') ?>
<?= $this->section('content') ?>
<div class="page-heading"><div><span class="page-kicker">Pilotage financier</span><h1>Situation des gains</h1><p>Répartition des frais et des commissions par opérateur.</p></div><span class="page-icon"><i class="bi bi-graph-up-arrow"></i></span></div>
<div class="gain-summary-grid"><article class="gain-summary gain-own"><span>Gains via les frais</span><strong><?= number_format($totalGains['frais'] ?? 0,2,',',' ') ?> <small>Ar</small></strong></article><article class="gain-summary gain-external"><span>Total des commissions</span><strong><?= number_format($totalCommissions,2,',',' ') ?> <small>Ar</small></strong></article></div>
<div class="gain-content-grid">
<section class="data-card"><div class="data-card-head"><div><span>Frais</span><h2>Par type d’opération</h2></div><i class="bi bi-cash-stack"></i></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Opération</th><th class="align-right">Total</th></tr></thead><tbody><?php foreach($gainsByTypeOperation as $nom=>$gain):?><tr><td><?= esc(ucfirst($nom)) ?></td><td class="align-right amount-cell"><?= number_format($gain,2,',',' ') ?> Ar</td></tr><?php endforeach;?></tbody></table></div></section>
<section class="data-card"><div class="data-card-head"><div><span>Commissions</span><h2>Par opérateur</h2></div><i class="bi bi-percent"></i></div><div class="data-table-wrap"><table class="data-table"><thead><tr><th>Opérateur</th><th class="align-right">Commission</th></tr></thead><tbody><?php foreach($gainsByOperateur as $nom=>$gain):?><tr><td><b><?= esc($nom) ?></b></td><td class="align-right commission-cell"><?= number_format($gain['frais_commission'] ?? 0,2,',',' ') ?> Ar</td></tr><?php endforeach;?></tbody></table></div></section>
</div>
<?= $this->endSection() ?>
